name: fraktalexplorer
description: "Fraktal Explorer für Mandelbrot und Julia-Mengen"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  window_size: ^0.1.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets (z. B. Bilder, Shader, etc.)
  # assets:
  #   - assets/images/

  # Fonts (optional)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
